import Head from "next/head";
import Layout from "../components/Layout.jsx";
import Hero from "../components/Hero.jsx";
import css from "../styles/Home.module.css"
import Services from "../components/Services.jsx";
import Menu from "../components/Menu.jsx";
import { client } from "../library/client";

export default function Home({pizzas}) {

  return (
    /*wrapper layout component with the others */
    <Layout>
      <div className={css.container}>
        <Head>
          <title>Foodie Go</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero />
          <Services />
          <Menu pizzas = {pizzas} />
        </main>
      </div>
    </Layout>
  );
}

/* as we are usig this , don't 
need to write code to render data to client side frm the db */
export const getServerSideProps = async()=>{
  const query = '*[_type == "pizza"]';
  const pizzas = await client.fetch(query);
  return {
    props: {
      pizzas
    }
  }
  
}
