import Head from "next/head";
import Layout from "../components/Layout.jsx";
import Hero from "../components/Hero.jsx";

export default function Home() {
  return (
    /*wrapper layout component with the others */
    <Layout>
      <div>
        <Head>
          <title>Foodie Go</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero />
        </main>
      </div>
    </Layout>
  );
}
